export const ACTIVE_ROUTE_CHANGED = 'ACTIVE_ROUTE_CHANGED';
export const APPROVE_CONDITIONS = 'APPROVE_CONDITIONS';
export const CONFIRM_INFORMATION = 'CONFIRM_INFORMATION';
export const TOGGLE_CHILD_BORN = 'TOGGLE_CHILD_BORN';
export const SET_NUMBER_OF_CHILDREN = 'SET_NUMBER_OF_CHILDREN';
export const SET_FODSEL_DATO = 'SET_FODSEL_DATO';
export const SET_TERMIN_DATO = 'SET_TERMIN_DATO';
export const SET_BEKREFTET_TERMIN_DATO = 'SET_BEKREFTET_TERMIN_DATO';
export const TOGGLE_RESIDED_IN_NORWAY_LAST_TWELVE_MONTHS =
	'RESIDED_IN_NORWAY_LAST_TWELVE_MONTHS';
export const TOGGLE_WORKED_IN_NORWAY_LAST_TWELVE_MONTHS =
	'WORKED_IN_NORWAY_LAST_TWELVE_MONTHS';
export const TOGGLE_OPPHOLD_NAA = 'TOGGLE_OPPHOLD_NAA';
export const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';
export const TOGGLE_RESIDING_IN_NORWAY_NEXT_TWELVE_MONTHS =
	'TOGGLE_RESIDING_IN_NORWAY_NEXT_TWELVE_MONTHS';
export const TOGGLE_RESIDING_IN_NORWAY_DURING_BIRTH =
	'TOGGLE_RESIDING_IN_NORWAY_DURING_BIRTH';
export const ADD_VISIT = 'ADD_COUNTRY';
export const EDIT_VISIT = 'EDIT_VISIT';
export const DELETE_VISIT = 'DELETE_COUNTRY';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAILED = 'POST_DATA_FAILED';
export const POST_DATA_REQUESTED = 'POST_DATA_REQUESTED';
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';
